name: Trigger Target Workflow

on:
  workflow_dispatch:
    inputs:
      target_service:
        description: 'Input a service name (e.g., demo-app)'
        required: true
      target_version:
        description: 'Input a version (e.g., v1.0.0)'
        required: true
      target_sha:
        description: 'Input a commit SHA (e.g., abc123)'
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Inputs
        run: |
          # Validate input presence
          if [[ -z "${{ github.event.inputs.target_service }}" || -z "${{ github.event.inputs.target_version }}" || -z "${{ github.event.inputs.target_sha }}" ]]; then
            echo "::error::All inputs (service, version, sha) are required."
            exit 1
          fi

          # Validate SHA format (should be 40 chars or 7+ chars for short SHA)
          if ! [[ "${{ github.event.inputs.target_sha }}" =~ ^[0-9a-f]{7,40}$ ]]; then
            echo "::error::Invalid SHA format. Must be a valid git commit hash."
            exit 1
          fi

          echo "::notice::Validated inputs: Service=${{ github.event.inputs.target_service }}, Version=${{ github.event.inputs.target_version }}, SHA=${{ github.event.inputs.target_sha }}"
      
      - name: Trigger Repository B Workflow
        env:
          TARGET_REPO_OWNER: "Yoono" # A variable can be created in the repository settings.
          TARGET_REPO_NAME: "target_workflow"
          EVENT_TYPE: "trigger-workflow"
        run: |
          # Set the required variables
          service="${{ github.event.inputs.target_service }}"
          version="${{ github.event.inputs.target_version }}"
          sha="${{ github.event.inputs.target_sha }}"

          # Prepare JSON payload
          payload=$(jq -n \
            --arg et "$EVENT_TYPE" \
            --arg s "$service" \
            --arg v "$version" \
            --arg sh "$sha" \
            '{"event_type": $et, "client_payload": {"service": $s, "version": $v, "sha": $sh}}')

          # Trigger the workflow in the target repository
          response=$(curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "Content-Type: application/json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/$TARGET_REPO_OWNER/$TARGET_REPO_NAME/dispatches" \
            -d "$payload")

          # Check HTTP status code
          status_code=$(curl -s -o /dev/null -w "%{http_code}" -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "Content-Type: application/json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/$TARGET_REPO_OWNER/$TARGET_REPO_NAME/dispatches" \
            -d "$payload")

          if [[ $status_code -ne 204 ]]; then
            echo "::error::Failed to trigger workflow. HTTP Status: $status_code"
            echo "::error::Response: $response"
            exit 1
          fi

          echo "::notice::Successfully triggered workflow in target repository"
